// Generated by scripts/irs-forms.mjs. Do not edit by hand.
// IRS forms, publications and sample notices stored in public/forms (U.S. government works, public domain).

export type IrsFileKind = "Form" | "Instructions" | "Publication" | "Sample notice";

export type IrsFile = {
  file: string;
  title: string;
  kind: IrsFileKind;
  sourceUrl: string;
  sizeKb: number;
  pages: number;
  // The page shown in the preview (IRS "Attention" cover sheets are skipped).
  previewPage: number;
  revised: string | null;
  preview: string;
};

export const irsFiles: Record<string, IrsFile> = {
  "f1040.pdf": {
    "file": "f1040.pdf",
    "title": "Form 1040",
    "kind": "Form",
    "sourceUrl": "https://www.irs.gov/pub/irs-pdf/f1040.pdf",
    "sizeKb": 215,
    "pages": 2,
    "previewPage": 1,
    "revised": "2026-01-02",
    "preview": "f1040.png"
  },
  "f2848.pdf": {
    "file": "f2848.pdf",
    "title": "Form 2848",
    "kind": "Form",
    "sourceUrl": "https://www.irs.gov/pub/irs-pdf/f2848.pdf",
    "sizeKb": 139,
    "pages": 2,
    "previewPage": 1,
    "revised": "2022-03-01",
    "preview": "f2848.png"
  },
  "i2848.pdf": {
    "file": "i2848.pdf",
    "title": "Instructions for Form 2848",
    "kind": "Instructions",
    "sourceUrl": "https://www.irs.gov/pub/irs-pdf/i2848.pdf",
    "sizeKb": 198,
    "pages": 8,
    "previewPage": 1,
    "revised": "2021-09-03",
    "preview": "i2848.png"
  },
  "f8821.pdf": {
    "file": "f8821.pdf",
    "title": "Form 8821",
    "kind": "Form",
    "sourceUrl": "https://www.irs.gov/pub/irs-pdf/f8821.pdf",
    "sizeKb": 71,
    "pages": 1,
    "previewPage": 1,
    "revised": "2021-01-23",
    "preview": "f8821.png"
  },
  "f9465.pdf": {
    "file": "f9465.pdf",
    "title": "Form 9465",
    "kind": "Form",
    "sourceUrl": "https://www.irs.gov/pub/irs-pdf/f9465.pdf",
    "sizeKb": 113,
    "pages": 2,
    "previewPage": 1,
    "revised": "2022-03-01",
    "preview": "f9465.png"
  },
  "f433f.pdf": {
    "file": "f433f.pdf",
    "title": "Form 433-F",
    "kind": "Form",
    "sourceUrl": "https://www.irs.gov/pub/irs-pdf/f433f.pdf",
    "sizeKb": 150,
    "pages": 4,
    "previewPage": 1,
    "revised": "2025-04-01",
    "preview": "f433f.png"
  },
  "f433a.pdf": {
    "file": "f433a.pdf",
    "title": "Form 433-A",
    "kind": "Form",
    "sourceUrl": "https://www.irs.gov/pub/irs-pdf/f433a.pdf",
    "sizeKb": 408,
    "pages": 8,
    "previewPage": 1,
    "revised": "2026-06-29",
    "preview": "f433a.png"
  },
  "f433d.pdf": {
    "file": "f433d.pdf",
    "title": "Form 433-D",
    "kind": "Form",
    "sourceUrl": "https://www.irs.gov/pub/irs-pdf/f433d.pdf",
    "sizeKb": 127,
    "pages": 4,
    "previewPage": 1,
    "revised": "2024-07-02",
    "preview": "f433d.png"
  },
  "f656b.pdf": {
    "file": "f656b.pdf",
    "title": "Form 656-B booklet",
    "kind": "Form",
    "sourceUrl": "https://www.irs.gov/pub/irs-pdf/f656b.pdf",
    "sizeKb": 1004,
    "pages": 32,
    "previewPage": 1,
    "revised": "2026-04-18",
    "preview": "f656b.png"
  },
  "f12277.pdf": {
    "file": "f12277.pdf",
    "title": "Form 12277",
    "kind": "Form",
    "sourceUrl": "https://www.irs.gov/pub/irs-pdf/f12277.pdf",
    "sizeKb": 83,
    "pages": 2,
    "previewPage": 1,
    "revised": "2025-11-07",
    "preview": "f12277.png"
  },
  "fw2.pdf": {
    "file": "fw2.pdf",
    "title": "Form W-2",
    "kind": "Form",
    "sourceUrl": "https://www.irs.gov/pub/irs-pdf/fw2.pdf",
    "sizeKb": 2100,
    "pages": 11,
    "previewPage": 2,
    "revised": "2026-08-12",
    "preview": "fw2.png"
  },
  "f1099nec.pdf": {
    "file": "f1099nec.pdf",
    "title": "Form 1099-NEC",
    "kind": "Form",
    "sourceUrl": "https://www.irs.gov/pub/irs-pdf/f1099nec.pdf",
    "sizeKb": 525,
    "pages": 6,
    "previewPage": 2,
    "revised": "2026-06-09",
    "preview": "f1099nec.png"
  },
  "f1099k.pdf": {
    "file": "f1099k.pdf",
    "title": "Form 1099-K",
    "kind": "Form",
    "sourceUrl": "https://www.irs.gov/pub/irs-pdf/f1099k.pdf",
    "sizeKb": 567,
    "pages": 6,
    "previewPage": 2,
    "revised": "2026-05-26",
    "preview": "f1099k.png"
  },
  "f1099int.pdf": {
    "file": "f1099int.pdf",
    "title": "Form 1099-INT",
    "kind": "Form",
    "sourceUrl": "https://www.irs.gov/pub/irs-pdf/f1099int.pdf",
    "sizeKb": 526,
    "pages": 7,
    "previewPage": 2,
    "revised": "2024-01-18",
    "preview": "f1099int.png"
  },
  "f12153.pdf": {
    "file": "f12153.pdf",
    "title": "Form 12153",
    "kind": "Form",
    "sourceUrl": "https://www.irs.gov/pub/irs-pdf/f12153.pdf",
    "sizeKb": 2164,
    "pages": 4,
    "previewPage": 1,
    "revised": "2022-07-21",
    "preview": "f12153.png"
  },
  "f9423.pdf": {
    "file": "f9423.pdf",
    "title": "Form 9423",
    "kind": "Form",
    "sourceUrl": "https://www.irs.gov/pub/irs-pdf/f9423.pdf",
    "sizeKb": 54,
    "pages": 2,
    "previewPage": 1,
    "revised": "2020-05-13",
    "preview": "f9423.png"
  },
  "f843.pdf": {
    "file": "f843.pdf",
    "title": "Form 843",
    "kind": "Form",
    "sourceUrl": "https://www.irs.gov/pub/irs-pdf/f843.pdf",
    "sizeKb": 110,
    "pages": 2,
    "previewPage": 1,
    "revised": "2024-12-20",
    "preview": "f843.png"
  },
  "f4506t.pdf": {
    "file": "f4506t.pdf",
    "title": "Form 4506-T",
    "kind": "Form",
    "sourceUrl": "https://www.irs.gov/pub/irs-pdf/f4506t.pdf",
    "sizeKb": 664,
    "pages": 2,
    "previewPage": 1,
    "revised": "2025-05-20",
    "preview": "f4506t.png"
  },
  "p1.pdf": {
    "file": "p1.pdf",
    "title": "Publication 1",
    "kind": "Publication",
    "sourceUrl": "https://www.irs.gov/pub/irs-pdf/p1.pdf",
    "sizeKb": 317,
    "pages": 2,
    "previewPage": 1,
    "revised": null,
    "preview": "p1.png"
  },
  "p594.pdf": {
    "file": "p594.pdf",
    "title": "Publication 594",
    "kind": "Publication",
    "sourceUrl": "https://www.irs.gov/pub/irs-pdf/p594.pdf",
    "sizeKb": 163,
    "pages": 8,
    "previewPage": 1,
    "revised": "2025-12-11",
    "preview": "p594.png"
  },
  "p1660.pdf": {
    "file": "p1660.pdf",
    "title": "Publication 1660",
    "kind": "Publication",
    "sourceUrl": "https://www.irs.gov/pub/irs-pdf/p1660.pdf",
    "sizeKb": 656,
    "pages": 4,
    "previewPage": 1,
    "revised": "2022-02-04",
    "preview": "p1660.png"
  },
  "p1450.pdf": {
    "file": "p1450.pdf",
    "title": "Publication 1450",
    "kind": "Publication",
    "sourceUrl": "https://www.irs.gov/pub/irs-pdf/p1450.pdf",
    "sizeKb": 127,
    "pages": 1,
    "previewPage": 1,
    "revised": "2020-02-27",
    "preview": "p1450.png"
  },
  "p783.pdf": {
    "file": "p783.pdf",
    "title": "Publication 783",
    "kind": "Publication",
    "sourceUrl": "https://www.irs.gov/pub/irs-pdf/p783.pdf",
    "sizeKb": 51,
    "pages": 4,
    "previewPage": 1,
    "revised": "2022-12-08",
    "preview": "p783.png"
  },
  "cp14_english.pdf": {
    "file": "cp14_english.pdf",
    "title": "Sample CP14 notice",
    "kind": "Sample notice",
    "sourceUrl": "https://www.irs.gov/pub/notices/cp14_english.pdf",
    "sizeKb": 104,
    "pages": 6,
    "previewPage": 1,
    "revised": "2025-11-07",
    "preview": "cp14_english.png"
  },
  "cp501_english.pdf": {
    "file": "cp501_english.pdf",
    "title": "Sample CP501 notice",
    "kind": "Sample notice",
    "sourceUrl": "https://www.irs.gov/pub/notices/cp501_english.pdf",
    "sizeKb": 390,
    "pages": 5,
    "previewPage": 1,
    "revised": null,
    "preview": "cp501_english.png"
  },
  "cp503_english.pdf": {
    "file": "cp503_english.pdf",
    "title": "Sample CP503 notice",
    "kind": "Sample notice",
    "sourceUrl": "https://www.irs.gov/pub/notices/cp503_english.pdf",
    "sizeKb": 156,
    "pages": 5,
    "previewPage": 1,
    "revised": "2018-01-08",
    "preview": "cp503_english.png"
  },
  "cp504_english.pdf": {
    "file": "cp504_english.pdf",
    "title": "Sample CP504 notice",
    "kind": "Sample notice",
    "sourceUrl": "https://www.irs.gov/pub/notices/cp504_english.pdf",
    "sizeKb": 262,
    "pages": 7,
    "previewPage": 1,
    "revised": null,
    "preview": "cp504_english.png"
  },
  "lt11_english.pdf": {
    "file": "lt11_english.pdf",
    "title": "Sample LT11 notice",
    "kind": "Sample notice",
    "sourceUrl": "https://www.irs.gov/pub/notices/lt11_english.pdf",
    "sizeKb": 99,
    "pages": 5,
    "previewPage": 1,
    "revised": "2019-08-29",
    "preview": "lt11_english.png"
  },
  "cp90_english.pdf": {
    "file": "cp90_english.pdf",
    "title": "Sample CP90 notice",
    "kind": "Sample notice",
    "sourceUrl": "https://www.irs.gov/pub/notices/cp90_english.pdf",
    "sizeKb": 257,
    "pages": 5,
    "previewPage": 1,
    "revised": null,
    "preview": "cp90_english.png"
  },
  "cp71c_english.pdf": {
    "file": "cp71c_english.pdf",
    "title": "Sample CP71C notice",
    "kind": "Sample notice",
    "sourceUrl": "https://www.irs.gov/pub/notices/cp71c_english.pdf",
    "sizeKb": 141,
    "pages": 6,
    "previewPage": 1,
    "revised": "2019-05-14",
    "preview": "cp71c_english.png"
  },
  "cp521_english.pdf": {
    "file": "cp521_english.pdf",
    "title": "Sample CP521 notice",
    "kind": "Sample notice",
    "sourceUrl": "https://www.irs.gov/pub/notices/cp521_english.pdf",
    "sizeKb": 241,
    "pages": 5,
    "previewPage": 1,
    "revised": null,
    "preview": "cp521_english.png"
  },
  "cp523_english.pdf": {
    "file": "cp523_english.pdf",
    "title": "Sample CP523 notice",
    "kind": "Sample notice",
    "sourceUrl": "https://www.irs.gov/pub/notices/cp523_english.pdf",
    "sizeKb": 314,
    "pages": 10,
    "previewPage": 1,
    "revised": "2019-04-30",
    "preview": "cp523_english.png"
  }
};
