// IRS files for the Library: downloads the PDFs listed in scripts/irs-forms.json into public/forms
// (blank forms, publications and sample notices are U.S. government works, public domain), renders a
// PNG preview of each (the first real page; IRS "Attention" cover sheets are skipped), and writes
// lib/irsFiles.ts.
//
//   node scripts/irs-forms.mjs            download anything missing, re-render previews
//   node scripts/irs-forms.mjs --refresh  re-download everything (new IRS revisions)
//
// Previews need Python with `pip install pypdfium2`.
import { execFileSync } from "node:child_process";
import fs from "node:fs";
import path from "node:path";

const root = path.resolve(import.meta.dirname, "..");
const listPath = path.join(root, "scripts/irs-forms.json");
const outDir = path.join(root, "public/forms");
const list = JSON.parse(fs.readFileSync(listPath, "utf8"));
const refresh = process.argv.includes("--refresh");
const headers = { "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 Chrome/128 Safari/537.36" };

fs.mkdirSync(outDir, { recursive: true });
for (const f of list) {
  const dest = path.join(outDir, f.file);
  if (fs.existsSync(dest) && !refresh) continue;
  const res = await fetch(f.url, { headers, signal: AbortSignal.timeout(60000) });
  if (!res.ok) throw new Error(`${res.status} ${f.url}`);
  const buf = Buffer.from(await res.arrayBuffer());
  if (buf.subarray(0, 5).toString() !== "%PDF-") throw new Error(`Not a PDF: ${f.url}`);
  fs.writeFileSync(dest, buf);
  const modified = res.headers.get("last-modified");
  const revised = modified ? new Date(modified).toISOString().slice(0, 10) : null;
  f.revised = revised && revised > "1971" ? revised : null; // some IRS files report the Unix epoch
  console.log(`Downloaded ${f.file}`);
}
fs.writeFileSync(listPath, `[\n${list.map((f) => `  ${JSON.stringify(f)}`).join(",\n")}\n]\n`);

const rendered = JSON.parse(
  execFileSync("python", [path.join(root, "scripts/render_pdf_previews.py"), ...list.map((f) => path.join(outDir, f.file))], {
    encoding: "utf8",
    maxBuffer: 1024 * 1024,
  })
);

const files = Object.fromEntries(
  list.map((f) => [
    f.file,
    {
      file: f.file,
      title: f.title,
      kind: f.kind,
      sourceUrl: f.url,
      sizeKb: Math.round(fs.statSync(path.join(outDir, f.file)).size / 1024),
      pages: rendered[f.file].pages,
      previewPage: rendered[f.file].previewPage,
      revised: f.revised ?? null,
      preview: f.file.replace(/\.pdf$/, ".png"),
    },
  ])
);

const ts = `// Generated by scripts/irs-forms.mjs. Do not edit by hand.
// IRS forms, publications and sample notices stored in public/forms (U.S. government works, public domain).

export type IrsFileKind = "Form" | "Instructions" | "Publication" | "Sample notice";

export type IrsFile = {
  file: string;
  title: string;
  kind: IrsFileKind;
  sourceUrl: string;
  sizeKb: number;
  pages: number;
  // The page shown in the preview (IRS "Attention" cover sheets are skipped).
  previewPage: number;
  revised: string | null;
  preview: string;
};

export const irsFiles: Record<string, IrsFile> = ${JSON.stringify(files, null, 2)};
`;
fs.writeFileSync(path.join(root, "lib/irsFiles.ts"), ts);

const skipped = Object.values(files).filter((f) => f.previewPage > 1);
const previewKb = Object.values(files).reduce((s, f) => s + fs.statSync(path.join(outDir, f.preview)).size / 1024, 0);
console.log(`${list.length} files · previews ${Math.round(previewKb)} KB · wrote lib/irsFiles.ts`);
if (skipped.length) console.log(`Skipped cover sheets: ${skipped.map((f) => `${f.file} → page ${f.previewPage}`).join(", ")}`);
